movieMvc/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using movieMvc.Models;
using System.Web.Helpers;
using System.Data.Entity.Validation;
using System.Diagnostics;
using Microsoft.AspNet.Identity.Owin;
using System.IO;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace movieMvc.Controllers
{
    [Authorize(Roles = "Admin")]
    public class MoviesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Movies
        public ActionResult Index()
        {

         

            var movie = db.MovieFunc.Include(t => t.MoviePhoto);

            return View(movie.ToList());
        }


        [AllowAnonymous]
        // GET: Movies/Details/5
        public ActionResult Details(int? id)
        {

            
            var userId = User.Identity.GetUserId();
            if (userId != null)
            {

                var UserMovie = db.UserMovie.Where(x => x.MovieID == id && x.UserId==userId).FirstOrDefault();
                
                
                if (UserMovie!=null)
                {
                    ViewData["Result"] = true;

                }
                else if (UserMovie==null)
                {

                    ViewData["Result"] = false;


                }

                ViewData["Role"] = "Anonymous";

                if (User.Identity.IsAuthenticated)
                {
                    ViewData["Role"] = "User";
                    if (isAdminUser())
                    {
                        ViewData["Role"] = "Admin";



                    }

                }
            }
            else {
                ViewData["Result"] = false;
                ViewData["Role"] = "Anonymous";
            }


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.MovieFunc.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }

            var temp = db.MoviePhotosFunc.Where(x => x.MovieID == id).Select(x=>x.PhotoID);
            var MoviePhotosList = db.PhotoFunc.Where(a => temp.Any(x => x == a.PhotoID));
            ViewData["MoviePhotosList"] = MoviePhotosList.ToList();


            var MovieArtistListMovieIDs = db.ArtistMovies.Where(x => x.MovieID == id).Select(x => x.ArtistID);
            var MovieArtistList = db.Artist.Where(a => MovieArtistListMovieIDs.Any(x => x == a.ArtistID));
            ViewData["MovieArtistList"] = MovieArtistList.ToList();




            return View(movie);
        }
        [Authorize(Roles = "Admin")]
        // GET: Movies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MovieID,MovieName,MovieReleaseDate,MovieGeneralScore,MovieGenre,MovieDirector,MovieTrailer,MovieInformation,MovieDuration")] Movie movie, Photo photo, MoviePhotos moviePhoto)
        {
            WebImage image = WebImage.GetImageFromRequest();
            byte[] toPutInDb = image.GetBytes();
            photo.PhotoContent = toPutInDb;
            moviePhoto.PhotoID = photo.PhotoID;
            moviePhoto.MovieID = movie.MovieID;


            try
            {
                if (ModelState.IsValid)
                {
                    db.MoviePhotosFunc.Add(moviePhoto);
                    db.PhotoFunc.Add(photo);
                    db.MovieFunc.Add(movie);
                    db.SaveChanges();
                    return RedirectToAction("CreateMovieArtist", "ArtistMovies", new { MovieID = movie.MovieID });
                }
            }
            catch (DbEntityValidationException dbEx)
            {
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        Trace.TraceInformation("Property: {0} Error: {1}",
                                                validationError.PropertyName,
                                                validationError.ErrorMessage);
                    }
                }
            }

            return View(movie);
        }

        // GET: Movies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.MovieFunc.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MovieID,MovieName,MovieReleaseDate,MovieGeneralScore,MovieGenre,MovieDirector,MovieTrailer,MovieInformation,MovieDuration")] Movie movie, HttpPostedFileBase[] uploadImages)
        {
            foreach (var image in uploadImages)
            {
                if (image.ContentLength > 0)
                {
                    byte[] imageData = null;
                    using (var binaryReader = new BinaryReader(image.InputStream))
                    {
                        imageData = binaryReader.ReadBytes(image.ContentLength);
                    }
                    var headerImage = new Photo
                    {
                        PhotoContent = imageData
                       

                    };
                    db.PhotoFunc.Add(headerImage);
                    db.SaveChanges();

                    var last2 = db.PhotoFunc.OrderByDescending(x => x.PhotoID).First();

                    MoviePhotos mv = new MoviePhotos() { PhotoID = last2.PhotoID, MovieID =movie.MovieID };

                    db.MoviePhotosFunc.Add(mv);
                    db.SaveChanges();


                }
            }
            if (ModelState.IsValid)
            {
                db.Entry(movie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(movie);
        }

        // GET: Movies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.MovieFunc.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Movie movie = db.MovieFunc.Find(id);
            db.MovieFunc.Remove(movie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [AllowAnonymous]
        public FileContentResult MoviesPhotos(int MovieID)
        {

            if (MovieID == null)
            {
                string fileName = HttpContext.Server.MapPath(@"~images/1.jpg");

                byte[] imageData = null;
                FileInfo fileInfo = new FileInfo(fileName);
                long imageFileLength = fileInfo.Length;
                FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read);
                BinaryReader br = new BinaryReader(fs);
                imageData = br.ReadBytes((int)imageFileLength);

                return File(imageData, "image/png");

            }


            else
            {

                // to get the user details to load user Image 
                var bdUsers = HttpContext.GetOwinContext().Get<ApplicationDbContext>();

                var userImage = bdUsers.MoviePhotosFunc.Where(x => x.MovieID == MovieID).FirstOrDefault();

                var lastUserImage = bdUsers.PhotoFunc.Where(x => x.PhotoID == userImage.PhotoID).FirstOrDefault();

                return new FileContentResult(lastUserImage.PhotoContent, "image/jpeg");
            }
           
        }
                private bool isAdminUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ApplicationDbContext context = new ApplicationDbContext();
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
                var s = UserManager.GetRoles(user.GetUserId());


                if (s[0].ToString() == "Admin")
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            return false;
        }

        [AllowAnonymous]
        public FileContentResult BringPhoto(int PhotoID)
        {

            if (PhotoID == null)
            {
                string fileName = HttpContext.Server.MapPath(@"~images/1.jpg");

                byte[] imageData = null;
                FileInfo fileInfo = new FileInfo(fileName);
                long imageFileLength = fileInfo.Length;
                FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read);
                BinaryReader br = new BinaryReader(fs);

movieMvc/Views/Movies/Create.cshtml
@model movieMvc.Models.Movie

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Movie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            @Html.LabelFor(model => model.MovieName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MovieName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MovieName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MovieReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MovieReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MovieReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MovieGeneralScore, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MovieGeneralScore, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MovieGeneralScore, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MovieGenre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MovieGenre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MovieGenre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MovieDirector, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MovieDirector, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MovieDirector, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MovieTrailer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MovieTrailer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MovieTrailer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MovieInformation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MovieInformation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MovieInformation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MovieDuration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MovieDuration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MovieDuration, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.MoviePhoto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="image" multiple />
                @Html.ValidationMessageFor(model => model.MoviePhoto, "", new { @class = "text-danger" })
            </div>           
        </div>
        /div>
        

       
        <div>
        </div>
      


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

movieMvc/Views/Movies/Delete.cshtml
@model movieMvc.Models.Movie

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MovieName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MovieName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MovieReleaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MovieReleaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MovieGeneralScore)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MovieGeneralScore)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MovieGenre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MovieGenre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MovieDirector)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MovieDirector)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MovieTrailer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MovieTrailer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MovieInformation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MovieInformation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MovieDuration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MovieDuration)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

movieMvc/Views/Movies/Details.cshtml
@model movieMvc.Models.Movie

@{
    ViewBag.Title = movieMvc.Resources.Home.Details;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    var MoviePhotosList = (List<movieMvc.Models.Photo>)ViewData["MoviePhotosList"];

}
@{
    var MovieArtistList = (List<movieMvc.Models.Artist>)ViewData["MovieArtistList"];

}
@{
    var Result = (Boolean)ViewData["Result"];

}
@{
    var Role = (String)ViewData["Role"];

}




<h2>@movieMvc.Resources.Home.MoviePhotos</h2>
<div class="banner-bottom">
    <div class="container">
        <div class="w3_agile_banner_bottom_grid">
            <div id="owl-demo" class="owl-carousel owl-theme">

                @foreach (var item in MoviePhotosList)
                {
                <div class="item">
                    <div class="w3l-movie-gride-agile w3l-movie-gride-agile1">

                        <img src="@Url.Action("BringPhoto", "Movies", new { PhotoID = item.PhotoID })" title="album-name" class="img-responsive" alt=" ">


                        @if (Role == "Admin")

    {
        var willDelete = Model.MoviePhoto.Where(x => x.PhotoID == item.PhotoID).Select(y => y.Id).FirstOrDefault();


                    @Html.ActionLink("Remove From Movie", "Delete", new { controller = "MoviePhotos", id = willDelete })
}


                    </div>
                    

                </div>

                }
            </div>
        </div>
    </div>
</div>

<h2>@movieMvc.Resources.Home.MovieArtists</h2>
<div class="banner-bottom">
    <div class="container">
        <div class="w3_agile_banner_bottom_grid">
            <div id="owl-demo2" class="owl-carousel owl-theme">

                @foreach (var item in MovieArtistList)
                {
                    <div class="item">
                        <div class="w3l-movie-gride-agile w3l-movie-gride-agile1">
                            <a href="@Url.Action("Details", "Artists", new { id = item.ArtistID })" class="hvr-shutter-out-horizontal">

                                <img src="@Url.Action("ArtistPhotos", "Artists", new { ArtistID = item.ArtistID })" title="album-name" class="img-responsive" alt=" ">
                                <div class="w3l-action-icon"><i class="fa fa-play-circle" aria-hidden="true"></i></div>
                            </a>
                            <div class="mid-1 agileits_w3layouts_mid_1_home">
                                <div class="w3l-movie-text">
                                    <h6><a href="@Url.Action("Details", "Artists", new { id = item.ArtistID })">@Html.DisplayFor(modelItem => item.ArtistName)</a></h6>
                                </div>
                                <div class="mid-2 agile_mid_2_home">
                                    <p>@Html.DisplayFor(modelItem => item.ArtistBirth)</p>
                                    <div class="block-stars">
                                        <ul class="w3l-ratings">
                                            @for (int i = 0; i < (int)Math.Ceiling(item.ArtisGeneralScore / 2); i++)
                    {
                        <li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
}

                                        </ul>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>

                            </div>
                            @if (Role == "Admin")

                            { var willDelete = Model.ArtistMovie.Where(x => x.ArtistID == item.ArtistID).Select(y => y.Id).FirstOrDefault();


                                @Html.ActionLink("Remove From Movie", "Delete", new { controller="ArtistMovies",id=willDelete})
}

                        </div>
                    </div>

                }
            </div>
        </div>
    </div>
</div>


























<hr />

<h2>@movieMvc.Resources.Home.Details</h2>


<div>


    <div>
        <dl class="dl-horizontal">






            <dt>
                @Html.DisplayNameFor(model => model.MovieName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MovieName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.MovieReleaseDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MovieReleaseDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.MovieGeneralScore)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MovieGeneralScore)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.MovieGenre)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MovieGenre)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.MovieDirector)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MovieDirector)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.MovieTrailer)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MovieTrailer)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.MovieInformation)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MovieInformation)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.MovieDuration)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MovieDuration)
            </dd>


        </dl>
    </div>

</div>
<p>

    @if (Result == true && Role=="User")
    {

        //başka controllerden function çağırırken
        @Html.ActionLink(@movieMvc.Resources.Home.Remove, "DeleteUserMovie", "Manage", new { MovieID = Model.MovieID }, null)

    }
    else if(Result == false && Role == "User")
    {
        @Html.ActionLink(@movieMvc.Resources.Home.AddMyFavoriteList, "AddUserMovie", "Manage", new { MovieID = Model.MovieID }, null)

    }

    @if (Role == "Admin")
    { 
    @Html.ActionLink(@movieMvc.Resources.Home.Edit, "Edit", new { id = Model.MovieID }) 
       <div><br /></div>
    @Html.ActionLink(@movieMvc.Resources.Home.BackToList, "Index")
    }
</p>

movieMvc/Views/Movies/Edit.cshtml
@model movieMvc.Models.Movie

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Movies", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Movie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MovieID)

        <div class="form-group">
            @Html.LabelFor(model => model.MovieName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MovieName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MovieName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MovieReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MovieReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MovieReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MovieGeneralScore, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MovieGeneralScore, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MovieGeneralScore, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MovieGenre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MovieGenre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MovieGenre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MovieDirector, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MovieDirector, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MovieDirector, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MovieTrailer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MovieTrailer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MovieTrailer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MovieInformation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MovieInformation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MovieInformation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MovieDuration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MovieDuration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MovieDuration, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.MoviePhoto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="span4">
                    <input type="file" name="uploadImages" multiple="multiple" class="input-files" />
                </span>
                
            </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

movieMvc/Views/Movies/Index.cshtml
@model IEnumerable<movieMvc.Models.Movie>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MovieName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MovieReleaseDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MovieGeneralScore)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MovieGenre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MovieDirector)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MovieTrailer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MovieInformation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MovieDuration)
        </th>
        <th></th>
    </tr>
    

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MovieName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MovieReleaseDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MovieGeneralScore)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MovieGenre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MovieDirector)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MovieTrailer)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MovieInformation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MovieDuration)
        </td>
        <td>
            <img src="@Url.Action("MoviesPhotos", "Movies",new {MovieID=item.MovieID })" style="width:160px;height:160px; background: #FFFFFF;
    margin: auto;
    -moz-border-radius: 60px;
    border-radius: 100px;
    padding: 6px;
    box-shadow: 0px 0px 20px #888;" />
        </td>
        
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MovieID }) |
            @Html.ActionLink("Details", "Details", new { id=item.MovieID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MovieID })
        </td>
       
    </tr>
   
}

</table>