movieMvc/Models/Artist.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using movieMvc.Resources;

namespace movieMvc.Models
{
    public class Artist
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ArtistID { get; set; }
        [Display(ResourceType = typeof(Home), Name = "ArtistName")]
        public string ArtistName { get; set; }
        [Display(ResourceType = typeof(Home), Name = "ArtistBirth")]
        [DisplayFormat(DataFormatString = "{0:d}")]
        [DataType(DataType.Date)]
        public DateTime ArtistBirth { get; set; }
        [Display(ResourceType = typeof(Home), Name = "ArtistPlaceOfBirth")]
        public string ArtistPlaceOfBirth { get; set; }
        [Display(ResourceType = typeof(Home), Name = "ArtistBiography")]
        public string ArtistBiography { get; set; }
        [Display(ResourceType = typeof(Home), Name = "ArtistGeneralScore")]
        public float ArtisGeneralScore { get; set; }


        public virtual ICollection<ArtistPhoto> ArtistPhoto { get; set; }
        public virtual ICollection<ArtistMovies> ArtistMovie { get; set; }

    }
}

movieMvc/Controllers/ArtistsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using movieMvc.Models;
using System.Web.Helpers;
using System.IO;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace movieMvc.Controllers
{
    [Authorize(Roles = "Admin")]

    public class ArtistsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Artists
        public ActionResult Index()
        {
            return View(db.Artist.ToList());
        }
        [AllowAnonymous]

        // GET: Artists/Details/5
        public ActionResult Details(int? id)
        {
            var userId = User.Identity.GetUserId();
            var UsersFavoriteArtists = db.UserArtist.Where(x => x.UserId == userId).Select(x => x.ArtistID);
            var UserArtist = db.UserArtist.Where(x => x.ArtistID == id).FirstOrDefault();
           
            if (userId != null)
            {

                var UserArtistResult = db.UserArtist.Where(x => x.ArtistID == id && x.UserId == userId).FirstOrDefault();


                if (UserArtistResult != null)
                {
                    ViewData["Result"] = true;

                }
                else if (UserArtistResult == null)
                {

                    ViewData["Result"] = false;


                }

                ViewData["Role"] = "Anonymous";

                if (User.Identity.IsAuthenticated)
                {
                    ViewData["Role"] = "User";
                    if (isAdminUser())
                    {
                        ViewData["Role"] = "Admin";



                    }

                }
            }
            else
            {
                ViewData["Result"] = false;
                ViewData["Role"] = "Anonymous";
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artist artist = db.Artist.Find(id);
            if (artist == null)
            {
                return HttpNotFound();
            }
            var temp = db.ArtistPhoto.Where(x => x.ArtistID == id).Select(x => x.PhotoID);
            var ArtistPhotoList = db.PhotoFunc.Where(a => temp.Any(x => x == a.PhotoID));


            ViewData["ArtistPhotoList"] = ArtistPhotoList.ToList();
            return View(artist);
        }

        // GET: Artists/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Artists/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ArtistID,ArtistName,ArtistBirth,ArtistPlaceOfBirth,ArtistBiography,ArtisGeneralScore")] Artist artist, Photo photo, ArtistPhoto artistPhoto)
        {

            WebImage ArtistImage = WebImage.GetImageFromRequest();
            byte[] toPutInDb = ArtistImage.GetBytes();
            photo.PhotoContent = toPutInDb;
            artistPhoto.PhotoID = photo.PhotoID;
            artistPhoto.ArtistID = artist.ArtistID;

            if (ModelState.IsValid)
            {
                db.PhotoFunc.Add(photo);
                db.ArtistPhoto.Add(artistPhoto);
                db.Artist.Add(artist);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(artist);
        }

        // GET: Artists/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artist artist = db.Artist.Find(id);
            if (artist == null)
            {
                return HttpNotFound();
            }
            return View(artist);
        }

        // POST: Artists/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ArtistID,ArtistName,ArtistBirth,ArtistPlaceOfBirth,ArtistBiography,ArtisGeneralScore")] Artist artist, HttpPostedFileBase[] uploadImages)
        {
            foreach (var image in uploadImages)
            {
                if (image.ContentLength > 0)
                {
                    byte[] imageData = null;
                    using (var binaryReader = new BinaryReader(image.InputStream))
                    {
                        imageData = binaryReader.ReadBytes(image.ContentLength);
                    }
                    var headerImage = new Photo
                    {
                        PhotoContent = imageData


                    };
                    db.PhotoFunc.Add(headerImage);
                    db.SaveChanges();

                    var last2 = db.PhotoFunc.OrderByDescending(x => x.PhotoID).First();

                    ArtistPhoto av = new ArtistPhoto() { PhotoID = last2.PhotoID, ArtistID = artist.ArtistID };

                    db.ArtistPhoto.Add(av);
                    db.SaveChanges();


                }
            }

            if (ModelState.IsValid)
            {
                db.Entry(artist).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(artist);
        }

        // GET: Artists/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artist artist = db.Artist.Find(id);
            if (artist == null)
            {
                return HttpNotFound();
            }
            return View(artist);
        }

        // POST: Artists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Artist artist = db.Artist.Find(id);
            db.Artist.Remove(artist);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        private bool isAdminUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ApplicationDbContext context = new ApplicationDbContext();
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
                var s = UserManager.GetRoles(user.GetUserId());


                if (s[0].ToString() == "Admin")
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            return false;
        }

        [AllowAnonymous]
        public FileContentResult ArtistPhotos(int ArtistID)
        {

            if (ArtistID == null)
            {
                string fileName = HttpContext.Server.MapPath(@"~images/1.jpg");

                byte[] imageData = null;
                FileInfo fileInfo = new FileInfo(fileName);
                long imageFileLength = fileInfo.Length;
                FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read);
                BinaryReader br = new BinaryReader(fs);
                imageData = br.ReadBytes((int)imageFileLength);

                return File(imageData, "image/png");

            }


            else
            {

                // to get the user details to load user Image 
                var bdUsers = HttpContext.GetOwinContext().Get<ApplicationDbContext>();

                var userImage = bdUsers.ArtistPhoto.Where(x => x.ArtistID == ArtistID).FirstOrDefault();

                var lastUserImage = bdUsers.PhotoFunc.Where(x => x.PhotoID == userImage.PhotoID).FirstOrDefault();

                return new FileContentResult(lastUserImage.PhotoContent, "image/jpeg");
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

movieMvc/Views/Artists/Create.cshtml
@model movieMvc.Models.Artist

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Artist</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ArtistName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArtistName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ArtistName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArtistBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArtistBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ArtistBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArtistPlaceOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArtistPlaceOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ArtistPlaceOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArtistBiography, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArtistBiography, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ArtistBiography, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArtisGeneralScore, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArtisGeneralScore, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ArtisGeneralScore, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ArtistPhoto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ArtistImage" />
                @Html.ValidationMessageFor(model => model.ArtistPhoto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

movieMvc/Views/Artists/Delete.cshtml
@model movieMvc.Models.Artist

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Artist</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ArtistName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ArtistName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ArtistBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ArtistBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ArtistPlaceOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ArtistPlaceOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ArtistBiography)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ArtistBiography)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ArtisGeneralScore)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ArtisGeneralScore)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

movieMvc/Views/Artists/Details.cshtml
@model movieMvc.Models.Artist

@{
    ViewBag.Title = movieMvc.Resources.Home.Details;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    var ArtistPhotoList = (List<movieMvc.Models.Photo>)ViewData["ArtistPhotoList"];

}
@{
    var Result = (Boolean)ViewData["Result"];

}
@{
    var Role = (String)ViewData["Role"];

}

<h2>@movieMvc.Resources.Home.ArtistPhotos</h2>
<div class="banner-bottom">
    <div class="container">
        <div class="w3_agile_banner_bottom_grid">
            <div id="owl-demo" class="owl-carousel owl-theme">

                @foreach (var item in ArtistPhotoList)
                {
                    <div class="item">
                        <div class="w3l-movie-gride-agile w3l-movie-gride-agile1">

                            <img src="@Url.Action("BringPhoto", "Movies", new { PhotoID = item.PhotoID })" title="album-name" class="img-responsive" alt=" ">
                            @if (Role == "Admin")

    {
        var willDelete = Model.ArtistPhoto.Where(x => x.PhotoID == item.PhotoID).Select(y => y.Id).FirstOrDefault();


                        @Html.ActionLink("Remove Photo", "Delete", new { controller = "ArtistPhotoes", id = willDelete })
}



                        </div>

                    </div>

                }
            </div>
        </div>
    </div>
</div>





<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ArtistName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ArtistName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ArtistBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ArtistBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ArtistPlaceOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ArtistPlaceOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ArtistBiography)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ArtistBiography)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ArtisGeneralScore)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ArtisGeneralScore)
        </dd>

    </dl>
</div>
<p>
   

    @if (Result == true && Role == "User")
    {

        //başka controllerden function çağırırken
        @Html.ActionLink("Remove", "DeleteUserArtist", "Manage", new { ArtistID = Model.ArtistID }, null)

    }
    else if (Result == false && Role == "User")
    {
        @Html.ActionLink("Add to My Favorite List", "AddUserArtist", "Manage", new { ArtistID = Model.ArtistID }, null)

    }

    @if (Role == "Admin")
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.ArtistID })
        <br />
        @Html.ActionLink("Back to List", "Index")
    }
</p>

movieMvc/Views/Artists/Edit.cshtml
@model movieMvc.Models.Artist

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Artists", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Artist</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ArtistID)

        <div class="form-group">
            @Html.LabelFor(model => model.ArtistName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArtistName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ArtistName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArtistBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArtistBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ArtistBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArtistPlaceOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArtistPlaceOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ArtistPlaceOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArtistBiography, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArtistBiography, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ArtistBiography, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArtisGeneralScore, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArtisGeneralScore, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ArtisGeneralScore, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <span class="span4">
                <input type="file" name="uploadImages" multiple="multiple" class="input-files" />
            </span>
            <span class="span2">
                <input type="submit" name="button" value="Upload" class="btn btn-upload" />
            </span>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

movieMvc/Views/Artists/Index.cshtml
@model IEnumerable<movieMvc.Models.Artist>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ArtistName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ArtistBirth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ArtistPlaceOfBirth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ArtistBiography)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ArtisGeneralScore)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ArtistName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ArtistBirth)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ArtistPlaceOfBirth)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ArtistBiography)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ArtisGeneralScore)
        </td>
        <td>
<img src="@Url.Action("ArtistPhotos", "Artists",new {ArtistID=item.ArtistID })" style="width:160px;height:160px; background: #FFFFFF;
    margin: auto;
    -moz-border-radius: 60px;
    border-radius: 100px;
    padding: 6px;
    box-shadow: 0px 0px 20px #888;" />
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ArtistID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ArtistID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ArtistID })
        </td>
    </tr>
}

</table>